# Generated by Django 4.2 on 2023-06-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_profile_delete_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pass',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
