# Generated by Django 4.2 on 2023-06-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0003_alter_pass_options_alter_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='coords_to_pass',
        ),
        migrations.RemoveField(
            model_name='level',
            name='pass_to_level',
        ),
    ]
