# Generated by Django 4.2 on 2023-06-30 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0004_remove_coordinates_coords_to_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_types',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='parent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='height',
            field=models.IntegerField(null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Middlename'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+799999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{7,15}$')]),
        ),
    ]
