# Generated by Django 4.2 on 2023-06-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0007_rename_beautytitle_pass_beauty_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('image_to_pass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adventure.pass')),
            ],
        ),
        migrations.RenameModel(
            old_name='Activity_types',
            new_name='Activ_types',
        ),
        migrations.RenameModel(
            old_name='Areas',
            new_name='Area',
        ),
        migrations.RenameModel(
            old_name='Coordinates',
            new_name='Coordinate',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
