# Generated by Django 4.2 on 2023-06-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0009_alter_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activ_types',
            new_name='Activity_types',
        ),
        migrations.AddField(
            model_name='pass',
            name='coord',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adventure.coordinate'),
        ),
        migrations.AddField(
            model_name='pass',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adventure.level'),
        ),
    ]
