# Generated by Django 4.2 on 2023-07-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0015_alter_level_autumn_alter_level_spring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval',
            old_name='images',
            new_name='image',
        ),
    ]
