# Generated by Django 4.2 on 2023-07-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0019_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
