# Generated by Django 4.2 on 2023-07-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0021_alter_user_email_user_email_unq'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='email_unq',
        ),
    ]
