# Generated by Django 4.2 on 2023-07-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0024_rename_user_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Pereval_Users', 'verbose_name_plural': 'Pereval_Users'},
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
