# Generated by Django 4.2 on 2023-07-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0028_alter_users_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='users',
            name='email_unq',
        ),
    ]
